compile:
	javac -cp "lib/json-20231013.jar:lib/javax.websocket-api-1.1.jar" src/KitchenDisplaySystem.java -d out/
run:
	java -cp "out:lib/json-20231013.jar:lib/javax.websocket-api-1.1.jar" KitchenDisplaySystem

